### ISSUE TITLE
声音在第2秒会停住

### ISSUE THREAD

**Issue by likaiwork** [huang1988519/SQRAudioPlayer#1]
1

**Comment by huang1988519** [comment]
@likaiwork 你好，地址已经失效，能否给新的地址？代码不怎么不会有功能更新了，但是有bug还会修复。

**Comment by huang1988519** [comment]
> 你好,项目还在维护吗? 直接播放这个地址,到第二秒会没有声音,十多秒后会回复,但是通过网页播放,或者下载播放不会
> http://tcdn44.tingchina.com/5C10B29C/8b62a75c86feada8af124f2bed147d71/yousheng/%E6%AD%A6%E4%BE%A0%E5%B0%8F%E8%AF%B4/%E4%BF%AE%E7%9C%9F%E7%95%8C%E8%B4%A5%E7%B1%BB/001.mp3

经过测试，《听中国》的资源文件对链接做了安全保护，过一段时间就会失效。使用最新的链接，在demo中是可以播放的。测试路径：
1. 访问 http://m.tingchina.com/ 手机网站
2. 随便选择一篇小说，开始听书，使用chrome抓取最新音频文件地址
3. 替换demo中 `- (IBAction)playTest:(id)sender` 中的播放地址

结果：正常播放。

**Comment by likaiwork** [comment]
还是不行的,你试下这个地址:
http://101.96.10.45/yst8-service.iphone2030.com/downloads/0/4/4/0446d29a9ebfede8f3ceaf9edc81a767.mp3

虽然能播放,但是把进度拖到第一秒去,第二秒开始到十多秒都播不了

**Comment by huang1988519** [comment]
多谢提Issue。

已经定位问题，为线程保活失败引起第二次网络拉取数据失败。
现在已经修改为 NSURLSession的方式。已经使用多个源测试，暂未发现问题。还请帮忙测试下。

**Comment by huang1988519** [comment]
和 likaiwork沟通，已经修复。
